from pico2d import *
import random

import framework
import gameworld

MOVE_SPEED_PPS = 300

TIME_PER_FLYING_ACTION = 0.6
FLYING_ACTION_PER_TIME = 1.0 / TIME_PER_FLYING_ACTION
FRAMES_PER_FLYING_ACTION = 2

TIME_PER_EXPLODE_ACTION = 0.5
EXPLODE_ACTION_PER_TIME = 1.0 / TIME_PER_EXPLODE_ACTION
FRAMES_PER_EXPLODE_ACTION = 5

enemy_explode_images = []

